export const MAX_SESSIONS = 15;
export const MAX_THERAPIES = 10;

export const TRANSLATIONS = {
  es: {
    title: 'REPÚBLICA BOLIVARIANA DE VENEZUELA',
    subtitle: 'MISIÓN MÉDICA CUBANA',
    cardTitle: 'TARJETA DE TRATAMIENTO EN REHABILITACIÓN',
    patientName: 'Nombre y Apellidos',
    clinicalHistory: 'Número de Historia Clínica',
    rehabRoom: 'Sala de Rehabilitación',
    state: 'Estado',
    birthDate: 'Fecha Nacimiento',
    age: 'Edad',
    sex: 'Sexo',
    idCard: 'Cédula de Identidad',
    healthConditions: 'Condiciones de Salud',
    therapies: 'Terapias',
    sessions: 'SESIONES DE TRATAMIENTO',
    session: 'Sesión',
    date: 'Fecha',
    printButton: 'Imprimir',
    saveButton: 'Guardar',
    resetButton: 'Restablecer',
    loadButton: 'Cargar Guardado',
    male: 'M',
    female: 'F',
  },
  en: {
    title: 'BOLIVARIAN REPUBLIC OF VENEZUELA',
    subtitle: 'CUBAN MEDICAL MISSION',
    cardTitle: 'REHABILITATION TREATMENT CARD',
    patientName: 'Name and Surname',
    clinicalHistory: 'Clinical History Number',
    rehabRoom: 'Rehabilitation Room',
    state: 'State',
    birthDate: 'Birth Date',
    age: 'Age',
    sex: 'Sex',
    idCard: 'ID Card',
    healthConditions: 'Health Conditions',
    therapies: 'Therapies',
    sessions: 'TREATMENT SESSIONS',
    session: 'Session',
    date: 'Date',
    printButton: 'Print',
    saveButton: 'Save',
    resetButton: 'Reset',
    loadButton: 'Load Saved',
    male: 'M',
    female: 'F',
  }
};